# Using Query:

# All SELECT statements generated by SQLAlchemy ORM are constructed by Query object.

# Query objects are initially generated using the query() method of the Session
'''
q = session.query(mapped class)         OR        q = Query(mappedClass, session)
'''

# Query object has all() method which returns a resultset in the form of list of objects. 
'''
result = session.query(Student).all()
'''

'''
from sqlalchemy import Column, Integer, String  
from sqlalchemy import create_engine
engine = create_engine('sqlite:///student.db', echo = True)
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

class Student(Base):
    __tablename__ = 'student'
    Id = Column(Integer,primary_key=True)
    Username = Column(String)
    Firstname = Column(String)
    Lastname = Column(String)
    School = Column(String)

from sqlalchemy.orm import sessionmaker
Session = sessionmaker(bind=engine)
session = Session()
result = session.query(Customers).all()

for row in result:
   print ("Username: ",row.Username, "Firstname:",row.Firstname, "Lastname:",row.Lastname, "School:",row.School)
'''
